#version 430
layout(local_size_x = 256) in;

struct Boid
{
    vec3 position;
    vec3 velocity;
    vec3 acceleration;
    mat4 model;
};

layout(std430, binding = 0) buffer inBoidBuffer
{
    Boid inBoids[];
};

layout(std430, binding = 1) buffer outBoidBuffer
{
    Boid outBoids[];
};

uniform float dT;

uniform float radiusOfInfluence;
uniform float radiusOfSeparation;
uniform float maxSpeed;
uniform float minSpeed;
uniform float maxForce;
uniform uint boxSize;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    // The local group exceeds the work group
    if (idx >= inBoids.length()) return;

    Boid boid = inBoids[idx];
    vec3 pos = boid.position;
    vec3 velocity = boid.velocity;

    float neighbourWeightSum = 0.0f;

    vec3 cohesionForce = vec3(0.0f);
    vec3 alignmentForce = vec3(0.0f);
    vec3 separationForce = vec3(0.0f);
    vec3 avoidanceForce = vec3(0.0f);

    float cohesionWeight = 10.0f;
    float alignmentWeight = 20.0f;
    float separationWeight = 100.0f;
    float avoidanceWeight = 10.0f;

    float box = float(boxSize);

    for (uint i = 0; i < inBoids.length(); ++i)
    {
        // Skip boid
        if (i == idx)
            continue;

        Boid otherBoid = inBoids[i];
        vec3 dirToOtherBoid = otherBoid.position - pos;

        float dist = length(dirToOtherBoid);

        float neighbourWeight = clamp(1.0f - dist / radiusOfInfluence, 0.0f, 1.0f);
        if (neighbourWeight <= 0.0f)
            continue;

        neighbourWeightSum += neighbourWeight;
        cohesionForce += dirToOtherBoid * neighbourWeight;
        alignmentForce += otherBoid.velocity * neighbourWeight;

        if (dist < radiusOfSeparation)
        {
            float separationStrength = (radiusOfSeparation - dist) / radiusOfSeparation;
            if (dist > 1e-5)
            {
                separationForce += -normalize(dirToOtherBoid) * separationStrength;
            }
            else
            {
                separationForce += -vec3(1.0, 0.0, 0.0) * separationStrength;
            }
        }
    }
    if (neighbourWeightSum > 0.0f)
    {
        cohesionForce /= neighbourWeightSum;
        alignmentForce /= neighbourWeightSum;
    }

    float avoidanceDistance = boxSize / 2 - boxSize / 2 * 0.2;
    if (pos.x > avoidanceDistance)
    {
        avoidanceForce += vec3(-1.0f, 0.0f, 0.0f) * (pos.x + avoidanceDistance);
    } 
    else if (pos.x < -avoidanceDistance)
    {
        avoidanceForce += vec3(1.0f, 0.0f, 0.0f) * (pos.x - avoidanceDistance);
    }
    if (pos.y > avoidanceDistance)
    {
        avoidanceForce += vec3(0.0f, -1.0f, 0.0f) * (pos.y + avoidanceDistance);
    }
    else if (pos.y < -avoidanceDistance)
    {
        avoidanceForce += vec3(0.0f, 1.0f, 0.0f) * (pos.y - avoidanceDistance);
    }
    if (pos.z > avoidanceDistance)
    {
        avoidanceForce += vec3(0.0f, 0.0f, -1.0f) * (pos.z + avoidanceDistance);
    }
    else if (pos.z < -avoidanceDistance)
    {
        avoidanceForce += vec3(0.0f, 0.0f, 1.0f) * (pos.z - avoidanceDistance);
    }

    vec3 desiredVelocity = cohesionForce * cohesionWeight 
                         + alignmentForce * alignmentWeight
                         + separationForce * separationWeight
                         + avoidanceForce * avoidanceWeight;

    vec3 acceleration = desiredVelocity - velocity;
    float accelerationMagnitude = length(acceleration);
    if (accelerationMagnitude > maxForce)
    {
        acceleration = (acceleration / accelerationMagnitude) * maxForce;
    }

    velocity += acceleration * dT;
    float speed = length(velocity);
    if (speed > maxSpeed)
    {
        velocity = (velocity / speed) * maxSpeed;
    }
    else if (speed < minSpeed && speed > 0.0f)
    {
        velocity = (velocity / speed) * minSpeed;
    }

    pos += velocity * dT;
    // Clamp it inside the box's dimensions
    pos = mod(pos + boxSize/2, boxSize) - boxSize/2;

    // Compute rotation
    vec3 forward = vec3(0.0f, 0.0f, 1.0f);
    vec3 right = vec3(1.0f, 0.0f, 0.0f);
    vec3 up = vec3(0.0f, 1.0f, 0.0f);

    if (speed > 1e-5)
    {
        forward = (velocity / speed); // normalize
        vec3 worldUp = abs(forward.y) < 0.999f ? vec3(0.0f, 1.0f, 0.0f) : vec3(1.0f, 0.0f, 0.0f);
        right = normalize(cross(worldUp, forward));
        up = normalize(cross(forward, right));
    }

    mat4 model = mat4(1.0f);
    model[0].xyz = right;
    model[1].xyz = up;
    model[2].xyz = forward;
    model[3].xyz = pos;

    outBoids[idx].position = pos;
    outBoids[idx].velocity = velocity;
    outBoids[idx].acceleration = acceleration;
    outBoids[idx].model = model;
}