#pragma once

#define OPENGL_VERSION_MAJOR 4
#define OPENGL_VERSION_MINOR 3
#define MIN_OPENGL_VERSION(x,y) (OPENGL_VERSION_MAJOR > (x) || (OPENGL_VERSION_MAJOR == (x) && OPENGL_VERSION_MINOR >= (y)))