#pragma once

#ifndef OPENGL_VERSION_MAJOR
#define OPENGL_VERSION_MAJOR 3
#elif OPENGL_VERSION_MAJOR > 4
#error(MYLIB::ERROR::OPENGL_VERSION_CAN_NOT_BE_GREATER_THAN_4.6)
#endif
#ifndef OPENGL_VERSION_MINOR
#define OPENGL_VERSION_MINOR 3
#elif (OPENGL_VERSION_MAJOR == 3 && OPENGL_VERSION_MINOR < 3) || \
      (OPENGL_VERSION_MAJOR == 4 && OPENGL_VERSION_MINOR < 0) || \
      (OPENGL_VERSION_MAJOR == 3 && OPENGL_VERSION_MINOR > 3) || \
      (OPENGL_VERSION_MAJOR == 4 && OPENGL_VERSION_MINOR > 6)
#error(MYLIB::ERROR::OPENGL_VERSION_MUST_BE_BETWEEN_3.3_AND_4.6)
#endif
#define MIN_OPENGL_VERSION(x,y) (OPENGL_VERSION_MAJOR > (x) || (OPENGL_VERSION_MAJOR == (x) && OPENGL_VERSION_MINOR >= (y)))